#!/bin/bash

# Source YunoHost helpers
source /usr/share/yunohost/helpers
source ynh_exec_as


# Retrieve arguments
app=__APP__
username=$1
final_path = ynh_app_setting_get $app final_path

# Generate a random password
password=$(ynh_string_random)

# Create the new user in Pilea
cd "$final_path" && ynh_exec_as $app php7.3 bin/console pilea:user:add "$username" "$password" -n