#!/bin/bash

# Source YunoHost helpers
source /usr/share/yunohost/helpers
source ynh_exec_as


# Retrieve arguments
app=__APP__
username=$1
final_path=$(ynh_app_setting_get "$app" final_path)

pushd $final_path
    user_exists=$(ynh_exec_as $app php7.3 bin/console pilea:user:exist "$username")
    if [ $user_exists -eq 0 ]
    then
        user_pass=$(ynh_string_random)
        ynh_exec_as $app php7.3 bin/console pilea:user:add "$username" "$user_pass" -n
    else
        ynh_exec_as $app php7.3 bin/console pilea:user:activate "$username"
    fi
popd
