#!/bin/bash

#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source ynh_install_php__3
source ynh_composer__2
source /usr/share/yunohost/helpers

#=================================================
# MANAGE SCRIPT FAILURE
#=================================================

ynh_abort_if_errors	# Stop script if an error is detected

#=================================================
# RETRIEVE ARGUMENTS FROM THE MANIFEST
#=================================================

# Retrieve app id
app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
admin=$YNH_APP_ARG_ADMIN
is_public=$YNH_APP_ARG_IS_PUBLIC

#=================================================
# CHECK IF THE APP CAN BE INSTALLED WITH THESE ARGS
#=================================================
ynh_print_info --message="Validating installation parameters..."

final_path=/var/www/$app
test ! -e "$final_path" || ynh_die "This path already contains a folder"

path_url=$(ynh_normalize_url_path $path_url)	# Check and normalize path

# Check web path availability
ynh_webpath_available $domain $path_url
# Register (book) web path
ynh_webpath_register $app $domain $path_url

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================
ynh_print_info --message="Storing installation settings..."

ynh_app_setting_set $app domain "$domain"
ynh_app_setting_set $app path_url "$path_url"
ynh_app_setting_set $app admin "$admin"
ynh_app_setting_set $app is_public "$is_public"

#=================================================
# STANDARD MODIFICATIONS
#=================================================
# INSTALL DEPENDENCIES
#=================================================
ynh_print_info --message="Installing dependencies..."

ynh_install_app_dependencies $pkg_dependencies

#=================================================
# INSTALL PHP
#=================================================
ynh_print_info --message="Installing PHP..."

ynh_install_php --phpversion="$php_app_version" --package="$php_additonal_packages"

#=================================================
# CREATE A MYSQL DB
#=================================================
ynh_print_info --message="Creating a MySQL database..."

db_name=$(ynh_sanitize_dbid $app)
db_user="$db_name"

# Generate random DES key & password
deskey=$(ynh_string_random 24)
ynh_app_setting_set "$app" deskey "$deskey"
ynh_app_setting_set "$app" db_name "$db_name"

# Initialize database
ynh_mysql_setup_db "$db_user" "$db_name"

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_print_info --message="Downloading source files..."

ynh_app_setting_set $app final_path "$final_path"
# Create tmp directory and fetch app inside
TMPDIR=$(mktemp -d)
ynh_setup_source "$TMPDIR"

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_print_info --message="Configuring system user..."

ynh_system_user_create $app # Create a dedicated system user

#=================================================
# NGINX CONFIGURATION
#=================================================
ynh_print_info --message="Configuring nginx web server..."

ynh_add_nginx_config
if [ "$path_url" = "/" ]
then
  # Replace "//" location (due to nginx template)
  # Prevent from replacing in "http://" expressions by excluding ":" as preceding character
  sed --in-place "s@\([^:]\)//@\1/@g" /etc/nginx/conf.d/$domain.d/$app.conf
else
  # Move prefix comment #for-subdir at end of lines
  sed --in-place "s/#for-subdir\(.*\)/\1 #for-subdir/g" /etc/nginx/conf.d/$domain.d/$app.conf
fi
ynh_store_file_checksum "/etc/nginx/conf.d/$domain.d/$app.conf"

#=================================================
# SPECIFIC SETUP
#=================================================
# INSTALL AND INIT COMPOSER
#=================================================
ynh_print_info --message="Installing Composer..."

ynh_install_composer --phpversion="$php_app_version" --workdir="$TMPDIR"

#=================================================
# CONFIGURE & INSTALL PILEA
#=================================================
ynh_print_info --message="Installing Pilea..."

pilea_conf="${TMPDIR}/.env"
cp ../conf/.env $pilea_conf

ynh_replace_string "database_name" "${db_name}" "$pilea_conf"
ynh_replace_string "database_user" "${db_user}" "$pilea_conf"
ynh_replace_string "database_password" "${db_pwd}" "$pilea_conf"
ynh_replace_string "app_secret" "${deskey}" "$pilea_conf"

# Restrict rights to Pilea user only
chmod 600 "$pilea_conf"

# Install files and set permissions
mv "$TMPDIR" "$final_path"

# Set rights on directory
chown -R $app: $final_path
chmod 755 $final_path

# Install dependencies and Pilea
pushd $final_path
  sudo -u $app pilea:install "$app"
popd

# Set up cron job
cron_path="/etc/cron.d/$app"
cp -a ../conf/pilea.cron "$cron_path"
chown root: "$cron_path"
chmod 644 "$cron_path"

ynh_replace_string "#USER#" "$app" "$cron_path"
ynh_replace_string "#DESTDIR#" "$final_path" "$cron_path"

#=================================================
# GENERIC FINALIZATION
#=================================================
# PHP-FPM CONFIGURATION
#=================================================
ynh_print_info --message="Configuring php-fpm..."

# Copy and set php-fpm7.2 configuration
ynh_add_fpm_config --phpversion="7.2"

#=================================================
# SETUP SSOWAT
#=================================================
ynh_print_info --message="Configuring SSOwat..."

# Make app public if necessary
if [ $is_public -eq 1 ]
then
  ynh_app_setting_set $app skipped_uris "/"
fi

#=================================================
# RELOAD SERVICES
#=================================================
ynh_print_info --message="Reloading services..."

ynh_systemd_action --service_name=nginx --action=reload
ynh_systemd_action --service_name=php7.2-fpm --action=reload

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --message="Installation of $app completed"