#!/bin/bash

# Treat unset variables as an error
set -u
#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers
source ynh_add_extra_apt_repo__3
source ynh_install_php__3

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --time --weight=1

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
db_name=$(ynh_app_setting_get $app db_name)
domain=$(ynh_app_setting_get "$app" domain)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE THE MYSQL DB
#=================================================
ynh_script_progression --message="Removing the MySQL database..." --time --weight=1

ynh_mysql_remove_db "$app" "$db_name"

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_script_progression --message="Removing app main directory..." --time --weight=1

ynh_secure_remove "/var/www/$app"

#=================================================
# REMOVE CRON JOB
#=================================================
ynh_script_progression --message="Removing cron job..." --time --weight=1

ynh_secure_remove "/etc/cron.d/$app"

#=================================================
# REMOVE PHP-FPM CONFIGURATION
#=================================================
ynh_script_progression --message="Removing php-fpm configuration..." --time --weight=1

ynh_remove_fpm_config

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression --message="Removing dependencies..." --time --weight=1

ynh_remove_app_dependencies
ynh_remove_php

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing nginx web server configuration..." --time --weight=1

ynh_remove_nginx_config


#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_script_progression --message="Removing the dedicated system user..." --time --weight=1

ynh_system_user_delete $app

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression --message="Removal of $app completed" --time --last
