#!/bin/bash

# Treat unset variables as an error
set -u
#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers
source ynh_add_extra_apt_repo__3
source ynh_install_php__3

#=================================================
# LOAD SETTINGS
#=================================================
ynh_print_info --message="Loading installation settings..."

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
db_name=$(ynh_app_setting_get $app db_name)
domain=$(ynh_app_setting_get "$app" domain)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE THE MYSQL DB
#=================================================
ynh_print_info --message="Removing the MySQL database..."

ynh_mysql_remove_db "$app" "$db_name"

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_print_info --message="Removing app main directory..."

ynh_secure_remove "/var/www/$app"

#=================================================
# REMOVE CRON JOB
#=================================================
ynh_print_info --message="Removing cron job..."

ynh_secure_remove "/etc/cron.d/$app"

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_print_info --message="Removing dependencies..."

ynh_remove_app_dependencies
ynh_remove_php

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_print_info --message="Removing nginx web server configuration..."

ynh_remove_nginx_config

#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_print_info --message="Removing the dedicated system user..."

ynh_system_user_delete $app

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --message="Removal of $app completed"