#!/bin/bash

# Treat unset variables as an error
set -u
#=================================================
# GENERIC STARTING
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get $app domain)
db_name=$(ynh_app_setting_get $app db_name)
domain=$(ynh_app_setting_get "$app" domain)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE DEPENDENCIES
#=================================================


ynh_remove_app_dependencies $pkg_dependencies
ynh_remove_php --phpversion=7.2
ynh_remove_app_dependencies $php_install_dependencies

#=================================================
# REMOVE THE MYSQL DB
#=================================================

ynh_mysql_remove_db "$app" "$db_name"

#=================================================
# REMOVE APP MAIN DIR
#=================================================

ynh_secure_remove "/var/www/$app"

#=================================================
# REMOVE CRON JOB
#=================================================

ynh_secure_remove "/etc/cron.d/$app"

#=================================================
# REMOVE NGINX AND PHP-FPM CONFIGURATION
#=================================================

ynh_remove_fpm7.2_config
ynh_remove_nginx_config

# Reload services
systemctl restart php7.2-fpm
systemctl reload nginx

#=================================================
# REMOVE DEDICATED USER
#=================================================

ynh_system_user_delete $app
